### ISSUE TITLE
Publish releases to maven central

### ISSUE THREAD

**Issue by beikov** [ingenieux/jbake-maven-plugin#18]
Hey I just saw that in 0.2.0 the JBake properties can be overridden in the plugin execution but I can't find that version on maven central: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22br.com.ingenieux%22%20AND%20a%3A%22jbake-maven-plugin%22

Any chance you can publish that and maybe the other releases on maven central too?

**Comment by beikov** [comment]
Since you didn't respond, I created my own plugin and published it to maven central.

**Comment by aldrinleal** [comment]
Thanks, thats so nice of you (as long as give credit, according to the licence, thats fine)

**Comment by beikov** [comment]
Since I redesigned the whole thing I am not sure where to give credits. Maybe you could tell me what you think should be adapted? See https://github.com/Blazebit/jbake-maven-plugin

**Comment by aldrinleal** [comment]
No, I won't review your code.

btw, it seems you need to be lectured on IP. I won't, though. Read this:

https://www.apache.org/licenses/LICENSE-2.0

Thank you

**Comment by beikov** [comment]
I wasn't asking you to review it, just notice that the code is completely different from yours.
I don't see how I am violating any IP that's why I was asking if you feel like there should be any attribution somewhere. Apparently you should be lectured on IP if you think that the mere idea or concept of the plugin deserves attribution because that's the only thing these two have in common.

I am going to add a link to your plugin in the README anyway because I obviously implemented it to be a better version of your plugin. I am happy to discuss _concrete_ issues you have with my plugin.

Btw. why didn't you respond to any of my request about publishing the artifacts? Maybe if you cared about the users of your plugin the way you cared about attribution we wouldn't even have this discussion. I was honestly trying to improve stuff here and all you do wrongly acuse me because you apparently feel uncomfortable with the situation.

**Comment by aldrinleal** [comment]
1. The 0.2.0 wasn't released due to serious regression issues I've had with other platforms, notably windows. 
2. Explaining why I didn't reply after 5 days (incl 2 in a Weekend) requires lots of personal explanation, considering I've got a day job :)
3. Nice. You've made a better plugin and you want my feedback, yet you weren't asked for a review. Be prepared for the worst part: Users complaining about regression and forking it if you don't reply on a weekend.

Now be productive: Leave me alone.

Thank you

**Comment by kinow** [comment]
@aldrinleal do you need any help to push 0.2.0 to Maven Central? Or to update it and fix the issues? Perhaps if you could list the issues I could try to help with some?

We built https://opennlp.apache.org with JBake, and we are using 0.0.9 right now.

I'm parameterizing the site generation, and noticed that the change to support properties in pom.xml being exported to JBake was added after 0.0.9 :-)

Happy to wait till a release is cut, and even happier if I can help in some way.

Sorry for resurrecting an old thread.

Cheers
Bruno

**Comment by aldrinleal** [comment]
@kinow Bruno, this plugin is mostly outdated, but the jbake guys are going to publish under a new groupId / orgId

(Dsclp)

**Comment by kinow** [comment]
Thanks for the quick reply @aldrinleal. Will check with them.

Bruno

**Comment by aldrinleal** [comment]
You could also fork it, provided you give credit.

É nóis na fita.

**Comment by kinow** [comment]
That will be the last option. First will check if there is any blocking issue I can help. There's still the alternative that is using jbake.properties, so it is not so urgent.

Nois! Valeu :-)

**Comment by aldrinleal** [comment]
I'd hop on jbake-dev (on googlegroups) to discuss it. Currently I'm unavailable to keep and maintain, let alone stand users complaning (and trust me - there's a lot)

Personally, I'd envisioned to make it easier to store all the rendered content in memory - and serve it straight from memory. Then, making enhancements to optimize static file serving (as far as allowing plugins, since the plugin itself could work as a standalone website, only changed on demand)

re: regression: one of the reasons I haven't kept it forward was due to jbake - due to a hard dependency on orientdb, having issues on Windows at that time - and I used to love Windows a lot until moment pushed me more into Linux

**Comment by jonbullock** [comment]
The plan is to publish the plugin under the org.jbake groupid from this repo: https://github.com/jbake-org/jbake-maven-plugin

**Comment by kinow** [comment]
Is there anything I could do to help with a release @jonbullock ?

**Comment by jonbullock** [comment]
Yeah could you test the plugin from the repo I've mentioned to see if it's ready to be published as is?
As there are a few open issues on this repo and I'm not sure if they need to be fixed or not before a release.
